### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by rsuhada** [AABoyles/LessWrong-Portable#5]
Hi, thanks for this package!
Unfortunately I did not get very far...
I run `nodejs buld.js hedonistic` and get:

    LessWrong-Portable/build.js:6`
    const { execSync } = require('child_process');
          ^

    SyntaxError: Unexpected token {
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:374:25)
        at Object.Module._extensions..js (module.js:417:10)
        at Module.load (module.js:344:32)
        at Function.Module._load (module.js:301:12)
        at Function.Module.runMain (module.js:442:10)
        at startup (node.js:136:18

Do you have any clue, what went wrong?
I have nodejs v4.2.6 on ubuntu 16.04.

Thank you very much!

**Comment by rsuhada** [comment]
After updating nodejs/npm this error went away. So the issue can be closed. 

Although now the scripts runs without error output/HedonisticImperative.epub is broken... but this is a clearly different issue...
